&&&& abre y cierra la barrafree
PARAMETERS ACCION,tipo
DO CASE
	CASE ACCION=1
		DO FORM BARRAFREE WITH tipo&& ABRE EL FORMULARIO AL INICIAR LA ACCION
	CASE ACCION=2
		IF WEXIST('BARRAFREE')
			RELEASE WINDOWS BARRAFREE && CIERRA EL FORMULARIO AL TERMINAR LA ACCION
		ELSE
			WAIT WINDOW "NO EXITES " NOWAIT
		ENDIF
ENDCASE
