PARAMETERS MESAEV
PUBLIC CMESAEV

DO CASE 
	CASE MESAEV=1
	CMESAEV='Enero'
	CASE MESAEV=2
	CMESAEV='Febrero'
	CASE MESAEV=3
	CMESAEV='Marzo'
	CASE MESAEV=4
	CMESAEV='Abril'
	CASE MESAEV=5
	CMESAEV='Mayo'
	CASE MESAEV=6
	CMESAEV='Junio'
	CASE MESAEV=7
	CMESAEV='Julio'
	CASE MESAEV=8
	CMESAEV='Agosto'
	CASE MESAEV=9
	CMESAEV='Septiembre'
	CASE MESAEV=10
	CMESAEV='Octubre'
	CASE MESAEV=11
	CMESAEV='Noviembre'
	CASE MESAEV=12
	CMESAEV='Diciembre'
ENDCASE

RETURN CMESAEV