&&&&& PROGRAMA QUE CONVIERTE LAS FECHAS TIPO CARACTER DE LAS CONSULTAS SQL A FORMATO DATE EN FOX
PARAMETERS MESSERRORSQL

DO CASE MESSERRORSQL
CASE "REFERENCE"$UPPER(MATRIZ[1,2])
	MESSAGEBOX("No Se Puede Eliminar, Existe Alguna Dependencia Relacionada A Este Elemento",64+0+0,"MENSAJE DE ERROR")
CASE "REMOTE"$UPPER(MATRIZ[1,2])
	MESSAGEBOX("Ésta Acción No Está Permitida",64+0+0,"MENSAJE DE ERROR")
CASE "FILE IS IN USE"$UPPER(MATRIZ[1,2])
	MESSAGEBOX("El Archivo Está En Uso",64+0+0,"MENSAJE DE ERROR")
CASE "CONNECTIONWRITE"$UPPER(MATRIZ[1,2]) OR "CONNECTIONREAD"$UPPER(MATRIZ[1,2]) OR "ERROR EN EL VÍNCULO DE COMUNICACIÓN"$UPPER(MATRIZ[1,2])
	DO sql_reconexionasql
*!*		DO ReconexionaFoxPro
CASE "PRIMARY KEY"$UPPER(MATRIZ[1,2])
	MESSAGEBOX("El Registro Ya Existe",64+0+0,"MENSAJE DE ERROR")
CASE "COMMUNICATION LINK FAILURE"$UPPER(MATRIZ[1,2])
	TABLEREVERT(.T.)
	DO sql_reconexionasql
*!*		DO ReconexionaFoxPro
OTHERWISE
	MESSAGEBOX(MATRIZ(3),55,'SQL')
ENDCASE



