&&&&&&&&&&&&&&&CREAR ARCHIVO PDF BASADO EN UN REPORTE&&&&&&&&&&&&&&&&&&&&&&
PARAMETERS CARPETA,REPORTE,NOMBREFILETMP
PUBLIC MRUTAPDF

&&&&&&SE CREA EL DIRECTORIO SI NO EXISTE&&&&&&&&&&
STORE CARPETA+"\" TO RUTAVOUCHTMP
IF !DIRECTORY('&RUTAVOUCHTMP')
	MD '&RUTAVOUCHTMP'
ENDIF
&&&&&&&&&&&&&&&&&configurar BULLZIP&&&&&&&&&&&&&&&&&&&&&

DIMENSION m.MATRICE(1)
m.NUMPRINTERS=APRINTERS(m.MATRICE)
FOR m.COUNTER=1 TO m.NUMPRINTERS
	IF ATC("BULLZIP",UPPER(m.MATRICE(m.COUNTER,1)))>0
		EXIT
	ENDIF
ENDFOR
m.NUMPRINTER=m.COUNTER
m.DEFAULTPRINTER=SET("Printer",3)

IF ATC("BULLZIP",UPPER(m.DEFAULTPRINTER))=0
*!*		SET PRINTER TO NAME m.MATRICE(m.NUMPRINTER),1
	SET PRINTER TO NAME m.MATRICE(1,1)
ENDIF
*!*		SELECT IESTADOCTA
*!*		STORE '&RUTAPDFS'+UCLIENTESINE+'.JPG' TO MRUTAPDF
*!*	STORE ALLTRIM(STR(NOORDEN)) TO CNORDEN
*!*	STORE "_ORDEN_&NPDF"+".PDF" TO NPDF
*!*	STORE ALLTRIM(ALLTRIM(THISFORM.CREadir(2))) TO APATH
*!*	STORE APATH + NPDF TO MRUTAPDF
STORE "&NOMBREFILETMP"+".PDF" TO NOMBREEXT
STORE RUTAVOUCHTMP+NOMBREEXT TO MRUTAPDF
*SET STEP ON
TRY
	LCOBJ = CREATEOBJECT("BullZIP.PDFPrinterSettings")
	WITH LCOBJ
		.SETVALUE("Output",MRUTAPDF)
		.SETVALUE("ShowSettings" ,"never")
		.SETVALUE("ShowPDF" ,"no")
		.SETVALUE("ShowProgressFinished" ,"no")
		.SETVALUE("ShowProgress" ,"no")
		.SETVALUE("Linearize" ,"no")
		.WRITESETTINGS(.T.)
	ENDWITH
CATCH
	MESSAGEBOX("Verifique Que Tenga Instalada La Impresora BullZip Para PDF",64+0+0,"SISTEMA &MPROGRA")
ENDTRY

IF VARTYPE(LCOBJ)='U'
RETURN .F.
ENDIF

IF ATC("BULLZIP",UPPER(m.DEFAULTPRINTER))=0
	STORE "Bullzip PDF Printer" TO m.DEFAULTPRINTER
	SET PRINTER TO NAME (m.DEFAULTPRINTER)
ENDIF
*!*	SET STEP ON
IF FILE('&MRUTAPDF')
	DELETE FILE '&MRUTAPDF'
ENDIF
*!*	SET STEP ON
SET ECHO OFF
SET TALK OFF
SET CONSOLE OFF
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
REPORT FORM &REPORTE TO PRINTER NOCONSOLE
RETURN '&MRUTAPDF'




*!*	IF DIRECTORY('&APATH')
*!*		THISFORM.OLEcontrol1.NAvigate2('&APATH')
*!*		THISFORM.OLEcontrol1.Visible= .T.
*!*	ELSE
*!*		THISFORM.OLEcontrol1.NAvigate2('')
*!*		THISFORM.OLEcontrol1.Visible= .F.
*!*	ENDIF


*!*	REPORT FORM VOUCHERPLANILLAPROF TO PRINTER NOCONSOLE
