HCONN=RCONN

OKBPRUEBACONNEX=SQLEXEC(HCONN,'USE CONSIS')
IF OKBPRUEBACONNEX<>1
	MESSAGEBOX("SU CONEXION AL SERVIDOR SE HA PERDIDO, INTENTARÉ CONECTARLO NUEVAMENTE. POR FAVOR ESPERE...",0+48+0+4096,"INTENTANDO RECONECTAR",3000)

	USE configuracionsistema SHARED &&&tabla permanente con la configuracion de IPS
	LCDSNLESS="dsn="+ALLTRIM(configuracionsistema.sqldsn)+";uid="+ALLTRIM(configuracionsistema.sqlUSER)+";pwd="+ALLTRIM(configuracionsistema.sqlPASS) &&&INFASA DRIVER SQLNCLI
	RCONN=SQLSTRINGCONNECT(LCDSNLESS,.F.)
	
	HCONN=RCON

	*HCONN=SQLSTRINGCONNECT(LCDSNLESS,.T.)

	OKBPRUEBACONNEX2=SQLEXEC(HCONN,'USE CONSIS')

	IF OKBPRUEBACONNEX2=1
		WAIT WINDOW 'RECONECTADO' NOWAIT
	ELSE
		WAIT WINDOW "CONEXION PERDIDA DEFINITIVAMENTE" NOWAIT
	ENDIF
ELSE
	WAIT WINDOW "CONEXION A SQL OK.." NOWAIT
ENDIF
